### ISSUE TITLE
Error when compiling on Windows 10 for 64bit

### ISSUE THREAD

**Issue by FedFod** [blueyeti/jit.realsense#4]
When compiling I get this error: 

CMake Error at CMakeLists.txt:25 (add_subdirectory):
  The source directory

    C:/Users/Federico Foderaro/Desktop/Lavoro_Christian_Curtis/jit.realsense/librealsense

  does not contain a CMakeLists.txt file.

Somebody can help?

**Comment by jcelerier** [comment]
(for further people coming to this issue : I guess the problem was that the submodule was not cloned correctly - you need to do `git submodule update --init`)

**Comment by FedFod** [comment]
Yes it was indeed! I would like to talk with you about multiple devices on a single computer. 
I've commented my experience on this thread in the Cycling74 forum:
https://cycling74.com/forums/intel-realsense-development

Would be really glad for any hint.

**Comment by jcelerier** [comment]
ah yes, somebody else reported this bug to me recently - I'm at work, I will try to integrate the fix tonight

**Comment by FedFod** [comment]
Thank you very much, it would be extremely great!!

**Comment by FedFod** [comment]
Hi Jean, sorry to ask again, but did you move forward? Could you maybe point me in the right direction on what to look for in the code?
